// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNme72lf0avyUVYSAf9PVDEt2vEdVPfE8',
    appId: '1:276226469795:web:7e48c792d99ee4e9517416',
    messagingSenderId: '276226469795',
    projectId: 'midterm-ppb',
    authDomain: 'midterm-ppb.firebaseapp.com',
    storageBucket: 'midterm-ppb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf31JODCW1HizbaJlMWQ4aJi_O-CB5zNk',
    appId: '1:276226469795:android:8e9a630279eb2b18517416',
    messagingSenderId: '276226469795',
    projectId: 'midterm-ppb',
    storageBucket: 'midterm-ppb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNme72lf0avyUVYSAf9PVDEt2vEdVPfE8',
    appId: '1:276226469795:web:88c1a5ff2c3c5c0d517416',
    messagingSenderId: '276226469795',
    projectId: 'midterm-ppb',
    authDomain: 'midterm-ppb.firebaseapp.com',
    storageBucket: 'midterm-ppb.firebasestorage.app',
  );
}
